kind: BucketClaim
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: BUCKET_CLAIM_NAME
  namespace: SAMPLE_APP_NAMESPACE
spec:
  # Reference to the BucketClass
  bucketClassName: BUCKET_CLASS_NAME
  # Protocols supported: s3
  protocols:
    - s3
